routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/employer/login/{hash}', 'Auth\LoginController@hashLogin');

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'isadmin'], function () {
    Route::get('/forms', 'FormsController@index');
    Route::get('/forms/create', 'FormsController@create');
    Route::get('/forms/edit/{id}', 'FormsController@edit');
    Route::post('/forms/makepdf', 'FormsController@makePdf');
    Route::post('/forms/edit/update/{id}', 'FormsController@update');
    Route::get('/forms/view-pdf/{id}', 'FormsController@viewPdf');
    Route::get('/forms/get/{filename}', ['as' => 'forms.getFormImage', 'uses' => 'FormsController@getImage']);
    Route::delete('/forms/delete/{id}', ['uses'=>'FormsController@delete', 'as'=>'forms.destroy']);

    #sponsors crud
    Route::resource('sponsors', 'SponsorController');
    Route::get('/sponsors/view-pdf/{id}', 'SponsorController@viewPdf');

    //Clients routes
    Route::get('/employer/create', 'EmployerController@create');
    Route::post('/employer/store', 'EmployerController@store');
    Route::get('/employer/list', ['uses'=>'EmployerController@showList', 'as'=>'employerList']);
    Route::get('/employer/edit-employer/{id}', 'EmployerController@edit');
    Route::post('/employer/edit-employer/update/{id}', 'EmployerController@update');
    Route::delete('/employer/delete/{id}', ['uses'=>'EmployerController@delete', 'as'=>'employer.destroy']);

    //Locations routes
    Route::get('/locations/create', 'LocationsController@create');
    Route::post('/locations/store', 'LocationsController@store');
    Route::get('/locations/list', 'LocationsController@showList');
    Route::get('/locations/edit-location/{id}', 'LocationsController@edit');
    Route::post('/locations/edit-location/update/{id}', 'LocationsController@update');
    Route::delete('/locations/delete/{id}', ['uses'=>'LocationsController@delete', 'as'=>'location.destroy']);

    //Offers routes
    Route::get('/offers/list/{approved?}', 'OfferController@showList');
    Route::get('/offers/make_approve/{offerId}', 'OfferController@make_approve');
});

Route::group(['middleware' => 'isemployer'], function () {
    Route::get('/student/photo/{filename}', array(
            'as' => 'student.getPhoto', 'uses' => 'HomeController@getImage'
        )
    );
    Route::get('/student/view-pdf/{id}', 'HomeController@viewPdf');
    Route::get('/student/get/{filename}', array(
        'as' => 'student.getSponsorForm', 'uses' => 'HomeController@getSponsorForm'
        )
    );

    Route::post('/offers/add', 'OfferController@add');
    Route::post('/offers/remove', 'OfferController@remove');
    Route::get('/offers/get', 'OfferController@get');
    Route::post('/offers/set_student_unvailable', 'OfferController@setStudentUnvailable');
    Route::get('/offers/students', 'OfferController@students');
    Route::post('/offers/upload_signed_form/{student_id}', 'OfferController@uploadSignedForm');
});
    #signedPdf not in group because employer AND admin can view pdf
    Route::get('/offers/signed/{id}', 'OfferController@getSignedForm')->middleware('auth');

app/Sponsor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sponsor extends Model
{
    protected $fillable = ['name', 'offer_form'];
}

app/Http/Controllers/SponsorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SponsorRequest;
use App\Sponsor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SponsorController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sponsors = Sponsor::paginate(10);
        return view('sponsors.index', compact('sponsors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sponsor = new Sponsor();
        return view('sponsors.create', compact('sponsor'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SponsorRequest $request)
    {
        #create sponsor
        $name = $request->get('name');
        $sponsor = Sponsor::create([
            'name' => $name
        ]);

        #if there is a pdf - upload it and save to database path
        $file = $request->file('offer_form');
        if($file){
            $fileName = str_slug($name, '-') . "-" . $sponsor->id ."." . $file->getClientOriginalExtension();
            Storage::disk('local')->put('uploads/sponsors/' . $fileName,  \File::get($file));
            $sponsor->update([
              'offer_form' => $fileName
            ]);
        }

        flash('Sponsor has been created', 'success');

        return redirect(url('sponsors'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sponsor = Sponsor::findOrFail($id);
        return view('sponsors.edit', compact('sponsor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SponsorRequest $request, $id)
    {
        $sponsor = Sponsor::findOrFail($id);
        $name = $request->get('name');
        $file = $request->file('offer_form');

        $data = [
          'name' => $name
        ];

        if($file){
            #delete previous pdf
            $this->deletePreviousFile($sponsor);

            $fileName = str_slug($name, '-') . "-" . $id . "." . $file->getClientOriginalExtension();
            Storage::disk('local')->put('uploads/sponsors/' . $fileName,  \File::get($file));
            $data['offer_form'] = $fileName;
        }

        $sponsor->update($data);
        flash('Sponsor has been updated', 'success');

        return redirect(url('sponsors'));
    }

    private function deletePreviousFile(Sponsor $sponsor)
    {
        if($sponsor->offer_form && Storage::disk('local')->has('uploads/sponsors/' . $sponsor->offer_form)){
            Storage::delete('uploads/sponsors/' . $sponsor->offer_form);
        }
        return true;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sponsor = Sponsor::findOrFail($id);
        $this->deletePreviousFile($sponsor);
        $sponsor->delete();
        flash('Sponsor has been deleted', 'success');
        return back();
    }

    public function viewPdf($id)
    {
        $entry = Sponsor::findOrFail($id);
        $path = storage_path('app/uploads/sponsors/'. $entry->offer_form);
        if (!\File::exists($path)){
            echo "File not found";
            return;
        }
        return \Response::make(file_get_contents($path), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="'.$entry->offer_form.'"'
        ]);
    }
}

resources/views/sponsors/_form.blade.php
@include('layouts.form-errors')
<div class="form-group">
    <label for="name">Name</label>
    {!! Form::text('name', $sponsor->name,
        ['id' => "name", 'class' => 'form-control', 'placeholder' => 'Sponsor name']) !!}
</div>
<div class="form-group">
    <label for="offer_form">Offer Form (pdf format)</label>
    {!! Form::file('offer_form', null,
        ['id' => "offer_form",
        'class' => 'form-control',
        'placeholder' => 'E-mail']) !!}
</div>
@if($sponsor->offer_form)
    <p>Uploaded Pdf: <a class="js-view-pdf" href="{{ url('/sponsors/view-pdf/' . $sponsor->id) }}">{{ $sponsor->offer_form }}</a></p>
    @include('blocks.modal_pdf')
@endif

<button type="submit" class="btn btn-default">Save</button>

resources/views/sponsors/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <h1>CREATE SPONSOR</h1>

            {!! Form::open(['url' => url('sponsors'), 'method' => 'POST', 'files' => true]) !!}
                @include('sponsors._form')
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/sponsors/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <h1>Edit SPONSOR</h1>

            {!! Form::open(['url' => route('sponsors.update', $sponsor->id),
                'method' => 'PATCH',
                'files' => true]) !!}

                @include('sponsors._form')

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/sponsors/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div>
                <h3>Sponsors LIST</h3>
            </div>
            <div>
                <a class="btn btn-default" href="{{ route('sponsors.create') }}">Add new</a>
            </div>
            </br>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="col-sm-7">Name</th>
                    <th class="col-sm-3">Offer Form</th>
                    <th class="col-sm-2">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($sponsors as $sponsor)
                    <tr>
                        <td>{{ $sponsor->name}}</td>
                        <td>
                            @if($sponsor->offer_form)
                                <a class="js-view-pdf" href="{{ url('/sponsors/view-pdf/' . $sponsor->id) }}">{{ $sponsor->offer_form }}</a>
                            @else
                                not uploaded
                            @endif
                        </td>
                        <td>
                            <div class="pull-left" style="margin-right: 5px;">
                                <form action="{{ route('sponsors.edit', $sponsor->id)  }}">
                                    <button type="submit" id="btn-form" class="btn btn-primary btn-xs">Edit</button>
                                </form>
                            </div>
                            <div class="pull-left">
                                {{Form::open(array('method'=>'delete',
                                  'onsubmit' => 'return confirm("Are you sure?")',
                                  'url' => route('sponsors.destroy', $sponsor->id)))}}
                                <button type="submit" name="submit" class="btn btn-danger btn-xs">Delete</button>
                                {{Form::close()}}
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $sponsors->links() }}
        </div>
    </div>
    @include('blocks.modal_pdf')
@endsection