routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/employer/login/{hash}', 'Auth\LoginController@hashLogin');

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'isadmin'], function () {
    Route::get('/forms', 'FormsController@index');
    Route::get('/forms/create', 'FormsController@create');
    Route::get('/forms/edit/{id}', 'FormsController@edit');
    Route::post('/forms/makepdf', 'FormsController@makePdf');
    Route::post('/forms/edit/update/{id}', 'FormsController@update');
    Route::get('/forms/view-pdf/{id}', 'FormsController@viewPdf');
    Route::get('/forms/get/{filename}', ['as' => 'forms.getFormImage', 'uses' => 'FormsController@getImage']);
    Route::delete('/forms/delete/{id}', ['uses'=>'FormsController@delete', 'as'=>'forms.destroy']);

    #sponsors crud
    Route::resource('sponsors', 'SponsorController');
    Route::get('/sponsors/view-pdf/{id}', 'SponsorController@viewPdf');

    //Clients routes
    Route::get('/employer/create', 'EmployerController@create');
    Route::post('/employer/store', 'EmployerController@store');
    Route::get('/employer/list', ['uses'=>'EmployerController@showList', 'as'=>'employerList']);
    Route::get('/employer/edit-employer/{id}', 'EmployerController@edit');
    Route::post('/employer/edit-employer/update/{id}', 'EmployerController@update');
    Route::delete('/employer/delete/{id}', ['uses'=>'EmployerController@delete', 'as'=>'employer.destroy']);

    //Locations routes
    Route::get('/locations/create', 'LocationsController@create');
    Route::post('/locations/store', 'LocationsController@store');
    Route::get('/locations/list', 'LocationsController@showList');
    Route::get('/locations/edit-location/{id}', 'LocationsController@edit');
    Route::post('/locations/edit-location/update/{id}', 'LocationsController@update');
    Route::delete('/locations/delete/{id}', ['uses'=>'LocationsController@delete', 'as'=>'location.destroy']);

    //Offers routes
    Route::get('/offers/list/{approved?}', 'OfferController@showList');
    Route::get('/offers/make_approve/{offerId}', 'OfferController@make_approve');
});

Route::group(['middleware' => 'isemployer'], function () {
    Route::get('/student/photo/{filename}', array(
            'as' => 'student.getPhoto', 'uses' => 'HomeController@getImage'
        )
    );
    Route::get('/student/view-pdf/{id}', 'HomeController@viewPdf');
    Route::get('/student/get/{filename}', array(
        'as' => 'student.getSponsorForm', 'uses' => 'HomeController@getSponsorForm'
        )
    );

    Route::post('/offers/add', 'OfferController@add');
    Route::post('/offers/remove', 'OfferController@remove');
    Route::get('/offers/get', 'OfferController@get');
    Route::post('/offers/set_student_unvailable', 'OfferController@setStudentUnvailable');
    Route::get('/offers/students', 'OfferController@students');
    Route::post('/offers/upload_signed_form/{student_id}', 'OfferController@uploadSignedForm');
});
    #signedPdf not in group because employer AND admin can view pdf
    Route::get('/offers/signed/{id}', 'OfferController@getSignedForm')->middleware('auth');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/all.css" rel="stylesheet">
    <link href="/css/print.min.css" rel="stylesheet">
    <link href="/css/jquery.fileupload.css" rel="stylesheet">
    <link href="/css/main.css?v=1" rel="stylesheet">

    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
    <!-- Scripts -->
    <script src="/js/app.js"></script>
    <script src="/js/all.js"></script>
    <script src="/js/print.min.js"></script>
    <script src="/js/main.js?v=1"></script>
    @yield('js-files')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/home') }}">
                        <img src="/img/slate-staffing-2.svg" class="img-responsive">
                        <small>(212) 461-4097</small>
                    </a>
                    {{--<a class="navbar-brand" href="{{ url('/home') }}">--}}
                        {{--{{ config('app.name', 'Laravel') }} <br><small>(212) 461-4097</small>--}}
                    {{--</a>--}}
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                        @else
                            @if (!Auth::user()->is_employer)
                            <li><a href="{{ url('/offers/list') }}">Offer carts</a></li>
                            <li><a href="{{ url('/forms') }}">Students</a></li>
                            <li><a href="{{ url('/employer/list') }}">Employers</a></li>
                            <li><a href="{{ route('sponsors.index') }}">Sponsors</a></li>
                            <li><a href="{{ url('/locations/list') }}">Locations</a></li>
                            @endif
                            <li><a href="#" style="cursor: default"><b>{{ Auth::user()->name }}</b></a></li>
                            <li>
                                <a href="{{ url('/logout') }}"
                                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                                    <span style="font-weight: normal" class="glyphicon glyphicon-log-out"></span>
                                    Sign out
                                </a>

                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            @include('flash::message')
        </div>

        @yield('content')
    </div>


    <footer>
        <div class="container">
            <div class="text-center">Slate Staffing, New York, (212) 461-4097</div>
        </div>
    </footer>

</body>
</html>

resources/views/layouts/email.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <style type="text/css" rel="stylesheet" media="all">
        /* Media Queries */
        @media only screen and (max-width: 500px) {
            .button {
                width: 100% !important;
            }
        }
    </style>
</head>

<?php

$style = [
    /* Layout ------------------------------ */


    /* Masthead ----------------------- */

    'email-masthead' => 'padding: 25px 0; text-align: center;',
    'email-masthead_name' => 'font-size: 25px; font-weight: bold; color: #555; text-decoration: none; text-shadow: 0 1px 0 white;',

    'email-body' => 'width: 100%; margin: 0; padding: 0; border-top: 1px solid #EDEFF2; border-bottom: 1px solid #EDEFF2; background-color: #FFF;',
    'email-body_inner' => 'width: auto; max-width: 570px; margin: 0 auto; padding: 0;',
    'email-body_cell' => 'padding: 35px;',

    'email-footer' => 'width: auto; max-width: 570px; margin: 0 auto; padding: 0; text-align: center;',
    'email-footer_cell' => 'color: #AEAEAE; padding: 35px; text-align: center;',

    /* Body ------------------------------ */

    'body_action' => 'width: 100%; margin: 30px auto; padding: 0; text-align: center;',
    'body_sub' => 'margin-top: 25px; padding-top: 25px; border-top: 1px solid #EDEFF2;',

    /* Type ------------------------------ */

    'anchor' => 'color: #3869D4;',
    'header-1' => 'margin-top: 0; color: #2F3133; font-size: 19px; font-weight: bold; text-align: left;',
    'paragraph' => 'margin-top: 0; color: #74787E; font-size: 16px; line-height: 1.5em;',
    'paragraph-sub' => 'margin-top: 0; color: #74787E; font-size: 12px; line-height: 1.5em;',
    'paragraph-center' => 'text-align: center;',

    /* Buttons ------------------------------ */

    'button' => 'display: block; display: inline-block; width: 200px; min-height: 20px; padding: 10px;
                 background-color: #3869D4; border-radius: 3px; color: #ffffff; font-size: 15px; line-height: 25px;
                 text-align: center; text-decoration: none; -webkit-text-size-adjust: none;',

    'button--green' => 'background-color: #22BC66;',
    'button--red' => 'background-color: #dc4d2f;',
    'button--blue' => 'background-color: #3869D4;',
];
?>

<?php $fontFamily = 'font-family: Arial, \'Helvetica Neue\', Helvetica, sans-serif;'; ?>

<body style="width: 100%; margin: 0; padding: 0; border-top: 1px solid #EDEFF2; border-bottom: 1px solid #EDEFF2; background-color: #FFF;">
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td style="" align="center">
            <table width="100%" cellpadding="0" cellspacing="0">
                <!-- Logo -->
                <tr>
                    <td style="{{ $style['email-masthead'] }}">
                        <a style="{{ $fontFamily }} {{ $style['email-masthead_name'] }}" href="{{ url('/') }}" target="_blank">
                            {{ config('app.name') }}
                        </a>
                    </td>
                </tr>

                <!-- Email Body -->
                <tr>
                    <td style="{{ $style['email-body'] }}" width="100%">
                        <table style="{{ $style['email-body_inner'] }}" align="center" width="570" cellpadding="0" cellspacing="0">
                            <tr>
                                <td style="{{ $fontFamily }} {{ $style['email-body_cell'] }}">
                                    <p style="{{ $style['paragraph'] }}">
                                        @yield('body')
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <!-- Footer -->
                <tr>
                    <td>
                        <table style="{{ $style['email-footer'] }}" align="center" width="570" cellpadding="0" cellspacing="0">
                            <tr>
                                <td style="{{ $fontFamily }} {{ $style['email-footer_cell'] }}">
                                    <p style="{{ $style['paragraph-sub'] }}">
                                        &copy; {{ date('Y') }}
                                        <a style="{{ $style['anchor'] }}" href="{{ url('/') }}" target="_blank">{{ config('app.name') }}</a>.
                                        All rights reserved.
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>

resources/views/layouts/form-errors.blade.php
@if(count($errors) > 0)
    <div class="form_errors alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/forms.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ config('app.url') }}/css/pdf-forms.css" rel="stylesheet">
    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    @yield('content')
</body>
</html>